feat: ✨ new hugo homepage
csunibo/csunibo.github.io pull request #20
Opened 2023-10-10 13:59 UTC by ali-benny

Prima bozza con i nostri progetti principali.

This closed Rinnovamento pagina principale #19

2023-10-10 13:59 UTC, ali-benny commented
C'è da vedere come si integra con gh Pages...

2023-10-10 14:35 UTC, foxyseta approved these changes

2023-10-10 15:22 UTC, foxyseta requested changes

2023-10-10 15:22 UTC, foxyseta commented on .github/workflows/gh-pages.yml
> +    runs-on: ubuntu-20.04
Userei `ubuntu-lastest`

2023-10-10 15:22 UTC, foxyseta commented on .github/workflows/gh-pages.yml
> +      - uses: actions/checkout@v3
Forse è già uscita la v4? Non ricordo

2023-10-10 15:22 UTC, foxyseta commented on .github/workflows/gh-pages.yml
> +        uses: peaceiris/actions-hugo@v2
Questa qui è la action ufficiale consigliata da GitHub per i progetti Hugo?

2023-10-10 16:23 UTC, ali-benny commented on .github/workflows/gh-pages.yml
> +      - uses: actions/checkout@v3
uh vero

2023-10-10 16:24 UTC, ali-benny commented on .github/workflows/gh-pages.yml
> +        uses: peaceiris/actions-hugo@v2
allora, ho preso questo file dalla repo del tema... controllo

2023-10-10 16:27 UTC, ali-benny commented on .github/workflows/gh-pages.yml
> +        uses: peaceiris/actions-hugo@v2
https://gohugo.io/hosting-and-deployment/hosting-on-github/

non mi sembra esserci questo step...
ma nella repo dedicata c'è https://github.com/peaceiris/actions-hugo

2023-10-10 22:58 UTC, foxyseta commented on .gitignore
> +# IDEs
Sostituirei questo gitignore con il gitignore ufficial di GitHub per Hugo. Sicuramente non vogliamo contenuti specifici per ambienti di sviluppo.

2023-10-10 23:00 UTC, foxyseta commented on README.md
> +
Mi sembra contenuto per la wiki. D'altro canto la wiki verrà presto integrata qua dentor e se la wiki non parte non si può leggere le istruzioni di come farla partire ahahahaah Quindi forse va già bene così come hai fatto tu.

2023-10-10 23:03 UTC, foxyseta commented on .github/workflows/gh-pages.yml
> +        uses: peaceiris/actions-hugo@v2
Finché non troviamo un motivo valido userei quella ufficiale di Hugo, che si presuppone valga per ogni tema

2023-10-11 00:11 UTC, foxyseta commented on .github/workflows/gh-pages.yml
> +        uses: peaceiris/actions-hugo@v2
Non mi sono messo a confrontare i file, ma "setup hugo" immagino installi Go e Hugo sul contenitore. Perché non prendiamo ispirazione dalla repo della wiki invece?

2023-10-11 05:31 UTC, ali-benny commented on .gitignore
> +# IDEs
Assolutamente, questo era il `.gitignore` che c'era prima

2023-10-11 05:33 UTC, ali-benny commented on README.md
> +
In ogni caso il link all'organizzazione su GitHub c'è già nelle icone sotto al logo sia in home che in about

2023-10-11 05:36 UTC, ali-benny commented on README.md
> +
Ops finte devi forse il deploy di Hugo... ahahah

Boh secondo me ha senso tenerlo qui perché quando cloni la repo hai le info, possiamo aggiungerlo anche alla wiki nuova... ditemi voi

2023-10-11 12:12 UTC, foxyseta approved these changes
Forse rimuoverei giusto la cartella `static/` siccome non usiamo il resumé (e git non traccia le cartelle vuote. Nel complesso comunque per me si può accettare. Davvero bel lavoro!

2023-10-11 13:43 UTC, merged