Created "Opportunità" page
csunibo/csunibo.github.io pull request #43
Opened 2024-01-25 13:56 UTC by MattiaFerrarini

Ho creato la pagina "Opportunità" come endpoint così da poter avere una struttura abbastanza organizzata.
Attualmente la pagina è solo in italiano e contiene le iniziative che conoscevo e ho trovato in questi giorni. Nel caso andasse bene, potrei creare la versione inglese nei prossimi giorni.
Alcune sezioni sono un po' carenti (ad esempio quella sui programmi estivi) o sbilanciate verso un certo ambito (ad esempio quella sulle summer school). Sperando in un minimo di contribuzioni, questa cosa si dovrebbe risolvere.
La sezione sui gruppi studenteschi nella parte riguardante le opportunità a Bologna sicuramente necessita integrazioni.

2024-01-25 14:10 UTC, foxyseta requested changes

2024-01-25 14:10 UTC, foxyseta commented on content/it/opportunities/_index.md
> +Se hai trovato o partecipato ad iniziative interessanti, potresti aggiungerle a questa raccolta? Nella [wiki](/it/wiki) è spiegato come fare!
Un collegamento alla pagina principale della wiki implica che neanche noi sappiamo di avere una pagina in particolare che sia davvero d'aiuto lol.

Io linkerei alla cartella (non all'intera repo!) di questa pagina su GitHub usando la variabile che si espande come nome della repo (non ricordo io nome su Hugo). Il testo del link diventerebbe quindi qualcosa tipo "modificare qui" o non so.

2024-01-25 14:53 UTC, MattiaFerrarini commented
Ho modificato config.yaml così opportunities si comporta come wiki. Ora alla fine di ogni pagina è presente il link "Modifica questa pagina" che rimanda direttamente al file su GitHub.

2024-01-25 15:28 UTC, foxyseta commented
> Ho modificato config.yaml così opportunities si comporta come wiki. Ora alla fine di ogni pagina è presente il link "Modifica questa pagina" che rimanda direttamente al file su GitHub.

Penso lo avessimo disabilitato per un problema che aveva con il multilingua. Lo hai collaudato su pagine non fatte da te in italiano e in inglese?

2024-01-25 15:28 UTC, foxyseta commented
(Questo problema che ricordavo è anche il motivo per cui non avevo suggerito questa soluzione, che sarebbe in teoria la più pulita, dall'inizio).

2024-01-25 16:11 UTC, MattiaFerrarini commented
Non mi sembra sia disabilitato, dato che in fondo a tutte le pagine della wiki compare "Modifica questa pagina", a meno che non ci siano altri modi per fare questo. Posso controllare più tardi. Comunque la modifica che ho fatto riguarda copia-incollare le impostazioni per la wiki e applicarle a opportunities all'interno di config. Non ho abilitato/disabilitato niente.
Per quanto riguarda i test in italiano, posso solo dirti che con la wiki funziona. Non esistendo i file su GitHub, i link delle mie pagine portano tutti a pagine inesistenti, ma gli url di queste dovrebbero essere giusti.
Per quanto riguarda le pagine in inglese, le uniche due che userebbero questa configurazione sono la wiki e opportunities e nessuna delle due ha una versione inglese attualmente.

2024-01-25 17:58 UTC, ali-benny commented
> > Ho modificato config.yaml così opportunities si comporta come wiki. Ora alla fine di ogni pagina è presente il link "Modifica questa pagina" che rimanda direttamente al file su GitHub.
> 
> Penso lo avessimo disabilitato per un problema che aveva con il multilingua. Lo hai collaudato su pagine non fatte da te in italiano e in inglese?

sembra che abbiano fixato il bug

2024-01-25 18:15 UTC, foxyseta commented
È abilitato sull'istanza di gh pages (https://csunibo.github.io) ma non su quella self-hostata. Lo avevo fixato io su https://github.com/csunibo/csunibo.github.io/issues/27 a quanto pare, ma ho potuto aggiornare solo sulla prima delle due istanze perché sulla seconda mancava la mia chiave ssh sulla macchina.

@samuelemusiani può darsi le mie chiavi non siano su 130.136.3.74?

2024-01-25 19:14 UTC, foxyseta approved these changes

2024-01-25 19:16 UTC, foxyseta commented
Ok ho ricevuto le chiavi e quindi aggiornato anche l'istanza su https://csunibo.students.cs.unibo.it. Ora che tutte le istanze hanno il pulsante "Modifica pagina" direi che le modifiche fatte vanno bene.

@MattiaFerrarini quando hai tempo puoi procedere con la traduzione direi, e magari dopo aver messo in produzione puoi spammare sui gruppi e invitare la gente ad aggiungere le attività di cui non eri a conoscenza.

2024-01-25 20:56 UTC, MattiaFerrarini commented
> Ok ho ricevuto le chiavi e quindi aggiornato anche l'istanza su https://csunibo.students.cs.unibo.it. Ora che tutte le istanze hanno il pulsante "Modifica pagina" direi che le modifiche fatte vanno bene.
> 
> @MattiaFerrarini quando hai tempo puoi procedere con la traduzione direi, e magari dopo aver messo in produzione puoi spammare sui gruppi e invitare la gente ad aggiungere le attività di cui non eri a conoscenza.

Va bene, quando riesco faccio la versione inglese. Per lo spam, magari avrebbe senso se lo facesse qualcuno di voi per dare più "legittimità" alla cosa, comunque questo si può vedere più avanti.

2024-01-25 21:52 UTC, foxyseta commented
> > Ok ho ricevuto le chiavi e quindi aggiornato anche l'istanza su https://csunibo.students.cs.unibo.it. Ora che tutte le istanze hanno il pulsante "Modifica pagina" direi che le modifiche fatte vanno bene.
> > @MattiaFerrarini quando hai tempo puoi procedere con la traduzione direi, e magari dopo aver messo in produzione puoi spammare sui gruppi e invitare la gente ad aggiungere le attività di cui non eri a conoscenza.
> 
> Va bene, quando riesco faccio la versione inglese. Per lo spam, magari avrebbe senso se lo facesse qualcuno di voi per dare più "legittimità" alla cosa, comunque questo si può vedere più avanti.

A me personalmente fa solo piacere far vedere che chiunque nel corso può implementare nuove funzionalità 🥰

2024-01-26 12:49 UTC, foxyseta commented
Se la traduzione già ti soddisfa ti posso accettare la PR.

2024-01-26 17:07 UTC, MattiaFerrarini commented
> Se la traduzione già ti soddisfa ti posso accettare la PR.

Sì, secondo me dovrebbe andare abbastanza bene.

2024-01-26 23:27 UTC, merged